// Framer Motion emitter — `<host>-motion.framer.js`.
//
// Turns the extracted durations + easing curves into ready-to-import
// Framer Motion `transition` presets and a few common `variants`
// (fade, slide-up, scale-in, stagger). Framer Motion is the dominant
// React animation library, so this is the highest-leverage motion
// emitter for the React ecosystem.

function bezier(raw) {
  if (!raw) return null;
  const m = String(raw).match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/i);
  if (m) return [parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3]), parseFloat(m[4])];
  const named = {
    linear: [0, 0, 1, 1], ease: [0.25, 0.1, 0.25, 1],
    'ease-in': [0.42, 0, 1, 1], 'ease-out': [0, 0, 0.58, 1], 'ease-in-out': [0.42, 0, 0.58, 1],
  };
  return named[String(raw).trim()] || null;
}

function camel(s) {
  return String(s || '').replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, '_$&');
}

export function formatFramerMotion(design) {
  const host = (() => { try { return new URL(design?.meta?.url).hostname.replace(/^www\./, ''); } catch { return 'site'; } })();
  const durations = Array.isArray(design?.motion?.durations) ? design.motion.durations : [];
  const easings   = Array.isArray(design?.motion?.easings)   ? design.motion.easings   : [];

  // Pick a default duration (the most common "medium" feel) and easing.
  const durSec = (d) => ((d.ms || parseInt(d.css || d.value || d, 10) || 300) / 1000);
  const defaultDur = durations.length
    ? durSec(durations[Math.min(2, durations.length - 1)])
    : 0.3;
  const sortedEase = [...easings].sort((a, b) => (b.count || 0) - (a.count || 0));
  const defaultEase = bezier(sortedEase[0]?.raw) || [0.25, 1, 0.5, 1];

  const lines = [
    '// Framer Motion presets — generated by designlang (motionlang)',
    `// Source: ${design?.meta?.url || host}`,
    `// ${new Date().toISOString()}`,
    '//',
    '//   import { transitions, variants } from \'./' + host + '-motion.framer\';',
    '//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"',
    '//               transition={transitions.base} />',
    '',
    '/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */',
    'export const easings = {',
  ];

  const easeEntries = [];
  sortedEase.forEach((e, i) => {
    const pts = bezier(e.raw);
    if (!pts) return;
    const key = e.family && e.family !== 'custom' ? camel(e.family) : `custom${i + 1}`;
    if (easeEntries.find((x) => x.key === key)) return;
    easeEntries.push({ key, pts, raw: e.raw, count: e.count });
  });
  if (easeEntries.length === 0) {
    easeEntries.push({ key: 'standard', pts: defaultEase, raw: 'fallback', count: 0 });
  }
  for (const { key, pts, count } of easeEntries) {
    lines.push(`  ${key}: [${pts.join(', ')}],${count ? ` // ${count}× on page` : ''}`);
  }
  lines.push('};', '');

  lines.push('/** Duration presets (seconds), extracted from the live page. */');
  lines.push('export const durations = {');
  if (durations.length) {
    for (const d of durations) {
      const name = camel(d.name || `ms${d.ms}`);
      lines.push(`  ${name}: ${durSec(d)},`);
    }
  } else {
    lines.push('  fast: 0.15,', '  base: 0.3,', '  slow: 0.5,');
  }
  lines.push('};', '');

  const primaryEaseKey = easeEntries[0].key;
  lines.push('/** Ready-to-spread Framer Motion transition objects. */');
  lines.push('export const transitions = {');
  lines.push(`  base:  { duration: ${defaultDur}, ease: easings.${primaryEaseKey} },`);
  lines.push(`  fast:  { duration: ${Math.max(0.1, defaultDur * 0.5).toFixed(3)}, ease: easings.${primaryEaseKey} },`);
  lines.push(`  slow:  { duration: ${(defaultDur * 1.8).toFixed(3)}, ease: easings.${primaryEaseKey} },`);
  lines.push(`  spring: { type: 'spring', stiffness: 320, damping: 30 },`);
  lines.push('};', '');

  lines.push('/** Common variants wired to the extracted timing. */');
  lines.push('export const variants = {');
  lines.push('  fade: {');
  lines.push('    hidden: { opacity: 0 },');
  lines.push('    show:   { opacity: 1, transition: transitions.base },');
  lines.push('  },');
  lines.push('  slideUp: {');
  lines.push('    hidden: { opacity: 0, y: 16 },');
  lines.push('    show:   { opacity: 1, y: 0, transition: transitions.base },');
  lines.push('  },');
  lines.push('  scaleIn: {');
  lines.push('    hidden: { opacity: 0, scale: 0.96 },');
  lines.push('    show:   { opacity: 1, scale: 1, transition: transitions.base },');
  lines.push('  },');
  lines.push('  stagger: {');
  lines.push('    hidden: {},');
  lines.push('    show:   { transition: { staggerChildren: ' + Math.max(0.04, defaultDur * 0.25).toFixed(3) + ' } },');
  lines.push('  },');
  lines.push('};', '');
  lines.push('export default { easings, durations, transitions, variants };');
  lines.push('');

  return lines.join('\n');
}
