import { resolveRef } from './_token-ref.js';

function walkLeaves(node, path = '') {
  const result = [];

  if (!node || typeof node !== 'object') {
    return result;
  }

  if ('$value' in node) {
    result.push({
      path,
      token: node,
    });
    return result;
  }

  for (const [key, value] of Object.entries(node)) {
    const nextPath = path ? `${path}.${key}` : key;
    result.push(...walkLeaves(value, nextPath));
  }

  return result;
}

function camelCase(name) {
  return name
    .split(/[-_.\s]+/)
    .filter(Boolean)
    .map((part, index) => {
      const clean = part.replace(/[^a-zA-Z0-9]/g, '');

      if (index === 0) {
        return clean.charAt(0).toLowerCase() + clean.slice(1);
      }

      return clean.charAt(0).toUpperCase() + clean.slice(1);
    })
    .join('');
}

function hexToUIColor(value) {
  if (typeof value !== 'string') {
    return null;
  }

  let hex = value.trim().replace('#', '');

  if (hex.length === 3) {
    hex = hex
      .split('')
      .map((c) => c + c)
      .join('');
  }

  if (hex.length !== 6) {
    return null;
  }

  const r = parseInt(hex.slice(0, 2), 16) / 255;
  const g = parseInt(hex.slice(2, 4), 16) / 255;
  const b = parseInt(hex.slice(4, 6), 16) / 255;

  return `UIColor(red: ${r}, green: ${g}, blue: ${b}, alpha: 1.0)`;
}

function dimensionToNumber(value) {
  if (typeof value === 'number') {
    return value;
  }

  if (typeof value !== 'string') {
    return null;
  }

  const match = value.match(/^(-?\d+(?:\.\d+)?)px$/);

  if (!match) {
    return null;
  }

  return Number(match[1]);
}

export function formatIosUIKit(tokens) {
  const lines = [];

  lines.push('// Generated by designlang v7.0.0');
  lines.push('import UIKit');
  lines.push('');

  // UIColor
  lines.push('extension UIColor {');

  const semanticColors = tokens?.semantic?.color;

  if (semanticColors) {
    lines.push('    // MARK: Semantic colors');

    for (const leaf of walkLeaves(semanticColors, 'semantic.color')) {
      if (leaf.token.$type !== 'color') continue;

      const value = resolveRef(tokens, leaf.path);
      const color = hexToUIColor(value);

      if (!color) continue;

      const parts = leaf.path.split('.');
      const name = camelCase(parts[parts.length - 1]);

      lines.push(`    static let ${name} = ${color}`);
    }
  }

  const primitiveColors = tokens?.primitive?.color;

  if (primitiveColors) {
    lines.push('');
    lines.push('    // MARK: Primitive colors');

    for (const leaf of walkLeaves(primitiveColors, 'primitive.color')) {
      if (leaf.token.$type !== 'color') continue;

      const value = resolveRef(tokens, leaf.path);
      const color = hexToUIColor(value);

      if (!color) continue;

      const parts = leaf.path.split('.');
      const name = camelCase(parts.slice(-2).join('-'));

      lines.push(`    static let ${name} = ${color}`);
    }
  }

  lines.push('}');
  lines.push('');

  // UIFont
  lines.push('extension UIFont {');

  const typography = tokens?.semantic?.typography;

  if (typography) {
    for (const leaf of walkLeaves(typography, 'semantic.typography')) {
      if (leaf.token.$type !== 'typography') continue;

      const value = leaf.token.$value;

      if (!value?.fontFamily) continue;

      const parts = leaf.path.split('.');
      const name = camelCase(parts[parts.length - 1]);

      lines.push(`    static func dl${name.charAt(0).toUpperCase()}${name.slice(1)}(`);
      lines.push('        size: CGFloat,');
      lines.push('        weight: UIFont.Weight = .regular');
      lines.push('    ) -> UIFont {');
      lines.push(
        `        return UIFont(name: "${value.fontFamily}", size: size)`
      );
      lines.push(
        '            ?? .systemFont(ofSize: size, weight: weight)'
      );
      lines.push('    }');
    }
  }

  lines.push('}');
  lines.push('');

  // Spacing
  lines.push('enum DLSpacing {');

  const spacing = tokens?.primitive?.spacing;

  if (spacing) {
    for (const leaf of walkLeaves(spacing, 'primitive.spacing')) {
      const value = leaf.token.$value;
      const number = dimensionToNumber(value);

      if (number === null) continue;

      const parts = leaf.path.split('.');
      const name = camelCase(parts.slice(-2).join('-'));

      lines.push(`    static let ${name}: CGFloat = ${number}`);
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}